# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76f90ada0989a26f54782a288bd18b46e30860464973c5d6e5aebe51def59e293fca1fbb0c6d5474bc2ff6baac5f3390a4116b149056f1a0048bbe223696c8c1

test:
  secret_key_base: 5f434c158a54d5286440dab891bf0f18ee55f890522741ed999a374bd7910fdabcba4ad7ee4658149f00640cd861ab387bf5401e47b1766d8aea39eb69e9bd39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
